on: [push]

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Docker CLI installation
        run: |
          apt-get update
          apt-get install -y ca-certificates curl
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: code.badbayou.com
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            code.badbayou.com/badbayou/badbayou
          flavor: |
            latest=true
          tags: |
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Install Updatecli in the runner
        uses: https://github.com/updatecli/updatecli-action@v2

      - name: Update helm chart versions with Updatecli
        if: github.event_name != 'pull_request'
        env:
          REGISTRY_USER: ${{ vars.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          # Extract the SHA tag from the docker metadata
          export NEW_APP_VERSION=$(echo "${{ steps.meta.outputs.tags }}" | grep -o 'sha-[a-f0-9]\{7\}' | head -1)
          echo "New app version: $NEW_APP_VERSION"

          # Run updatecli to update helm chart versions and create PR
          updatecli apply --config updatecli.yaml
